### ISSUE TITLE
Add content to the site

### ISSUE THREAD

**Issue by GNYniamh** [GNYniamh/StaticSite#12]
Add content, this can include tables, images, navigation to resources.

Please note that since a few folks have contributed to this the topic has been determined as "Squishmallows", an opened tab will be named "breaking news" so let's follow this format!

**Comment by Milind-Palaria** [comment]
hey @GNYniamh i would like to contribute to this as per your instructions. Can you assign this to me?

also, i would like to use normal CSS instead of bootstrap CSS, if that is ok with you.

**Comment by GNYniamh** [comment]
@Milind-Palaria Sure thing, go for it!  The project is sort of intended as a sandbox for folks to learn so that is OK.

**Comment by GNYniamh** [comment]
@Vlixierr Thank you for adding a list and even fixing up some styling and doctype tags! #13

**Comment by GNYniamh** [comment]
@Milind-Palaria #16 ; @Vlixierr #14 ; @WabiSabi218 #17 resolved thanks!
